import os
import subprocess
import requests
from fastapi import FastAPI, Request, BackgroundTasks

app = FastAPI()

def process_and_reply_github(issue_url: str, comment_body: str):
    try:
        ollama_res = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "qwen2.5:1.5b",
                "prompt": f"You are a coding assistant. A user posted this GitHub comment:\n'{comment_body}'\nProvide a clear, concise resolution plan.",
                "stream": False
            },
            timeout=60
        )
        reply_text = ollama_res.json().get("response", "No output generated by Qwen.")
    except Exception as e:
        reply_text = f"Failed to reach local Ollama instance: {e}"

    formatted_reply = f"🤖 **Local Qwen Assistant:**\n\n{reply_text}"
    env = os.environ.copy()
    if "GITHUB_PAT" in env:
        env["GH_TOKEN"] = env["GITHUB_PAT"]

    subprocess.run(
        ["gh", "issue", "comment", issue_url, "--body", formatted_reply],
        env=env,
        capture_output=True,
        text=True
    )

@app.post("/github-webhook")
async def handle_github_webhook(request: Request, background_tasks: BackgroundTasks):
    payload = await request.json()
    comment_body = payload.get("comment", {}).get("body", "")
    issue_url = payload.get("issue", {}).get("html_url") or payload.get("issue", {}).get("url", "")

    if any(keyword in comment_body for keyword in ["/action", "/approve"]):
        print(f"[AIDA DAEMON] Triggered by comment: {comment_body}")
        background_tasks.add_task(process_and_reply_github, issue_url, comment_body)
        return {"status": "dispatched_to_qwen", "action": comment_body}

    return {"status": "ignored"}
